import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex">
          {/* left side  */}
          <div className="w-[14%] md:w-[8%] lg:w-[16] xl:w-[14%] bg-red-200">
            fasfd
          </div>
          {/* right side  */}
          <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] bg-red-300"></div>
        </div>
      </body>
    </html>
  );
}
